version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/app

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:5000
    volumes:
      - ./client:/app
    depends_on:
      - api
